### ISSUE TITLE
Erro no templante abandoned-cart

### ISSUE THREAD

**Issue by talissonf** [ecomclub/transactional-mails#21]
```bash
(node:19839) UnhandledPromiseRejectionWarning: TypeError: /media/talisson/41A9192637BAF6D2/e-com-club/app-ses/node_modules/@ecomplus/transactional-mails/views/abandoned-cart.ejs:106
    104|                                       <% cart.items.forEach(item => { %>
    105|                                         <tr style="border-top-width:1px;border-top-color:#e5e5e5;border-top-style:solid">
 >> 106|                                           <td style="width:400px;max-width:33.333%;padding:10px; "><img class="max-width" border="0" style="display:block;color:#000000;text-decoration:none;font-family:Helvetica, arial, sans-serif;font-size:16px;max-width:100% !important;width:50%;height:auto !important;" src="<%= item.picture.small.url %>" alt="" width="100"></td>
    107|                                           <td style="width:400px;max-width:33.333%;padding:10px;"><div style="text-align: center;"><%= ecomUtils.name(item) %></div></td>
    108|                                           <td style="width:50px;max-width:10%;"><div style="text-align: center;">x <%= item.quantity %></div></td>
    109|                                           <td style="width:50px;max-width:10%;"><div style="text-align: center;"><%= ecomUtils.formatMoney(ecomUtils.price(item) * item.quantity, 'BRL', 'pt_br') %></div></td>

Cannot read property 'small' of undefined
    at cart.items.forEach.item (/media/talisson/41A9192637BAF6D2/e-com-club/app-ses/node_modules/@ecomplus/transactional-mails/views/abandoned-cart.ejs:95:39)
    at Array.forEach (<anonymous>)
    at eval (/media/talisson/41A9192637BAF6D2/e-com-club/app-ses/node_modules/@ecomplus/transactional-mails/views/abandoned-cart.ejs:92:19)
    at abandoned-cart (/media/talisson/41A9192637BAF6D2/e-com-club/app-ses/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/media/talisson/41A9192637BAF6D2/e-com-club/app-ses/node_modules/ejs/lib/ejs.js:254:36)
    at Object.exports.renderFile (/media/talisson/41A9192637BAF6D2/e-com-club/app-ses/node_modules/ejs/lib/ejs.js:485:10)
    at Object.sass.render [as callback] (/media/talisson/41A9192637BAF6D2/e-com-club/app-ses/node_modules/@ecomplus/transactional-mails/src/lib/render.js:70:15)
    at options.success (/media/talisson/41A9192637BAF6D2/e-com-club/app-ses/node_modules/node-sass/lib/index.js:308:32)
(node:19839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19839) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
@vitorrgg  O template de carrinho abandonado ta com esse erro de parse, se puder olhar depois.

**Comment by vitorrgg** [comment]
Me envia o body do cart que você usou no teste @talissonf ?

**Comment by talissonf** [comment]
@vitorrgg o _id do cart é esse 5e1e579f62887026009bb711, eu salvo só o _id e depois o app pega o body na api.

**Comment by vitorrgg** [comment]
Arrumei lá.
